[package]
name = "micromcs"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
proptest = "1.9.0"

[dependencies]
reqwest = { version = "0.13", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
